cleanlab/cleanlab-studio

cleanlab_cli/settings.py

From https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html:
> If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.
This patch also switches the directory from ".cleanlab" to just "cleanlab". There's no need to prepend a "." when it's already in the (hidden) config directory.

Follow XDG spec for config directory

---

cleanlab_cli/decorators/previous_state.py
tests/test_schema.py

This fixes the tests. This patch also makes the `assert_success_else_error_output` print a traceback for the captured exception to make it easier to debug tests.

Create settings directory if it doesn't exist

---

cleanlab_cli/dataset/schema_helpers.py

Sampling up to 10K random rows from up to the first 200K rows of the dataset should be enough for us to get a sufficiently representative sample of the Dataset to do type inference. This could result in incorrect type inferences for some very peculiarly constructed datasets, but the schema just has to be a good guess rather than perfect, so this should be fine.
Also, this keeps our schema generation step to <1s for a 1GB dataset.

Cap number of rows in Datasets sampled from to 200K

---

cleanlab_cli/classes/excel_dataset.py
cleanlab_cli/dataset/schema_helpers.py

- Optimize reading of datasets by reading rows as values rather than as key-value pairs
- Optimize `ExcelDataset` to use `iget_array` instead of `iget_records`, same idea as above

Read streaming array instead of records

---

cleanlab_cli/api_service.py
cleanlab_cli/cleanset/download.py

`cleanlab cleanset download` now accepts an `--all` flag to download all Cleanlab columns, instead of just the `clean_label` column.

--all flag to allow downloading of all Cleanlab columns

---

DEVELOPMENT.md
cleanlab_cli/__init__.py
cleanlab_cli/dataset/schema_helpers.py
cleanlab_cli/settings.py
cleanlab_cli/version.py
setup.py

1. Added full details about how versioning is handled for CLI in `development.md`
2. Based on (1), added `MIN_SCHEMA_VERSION` and `MIN_SETTINGS_VERSION` to `version.py` and removed `VALID_VERSIONS`
3. Added `semver` package as dependency, for checking schemas / settings against CLI min versions
Settings migration support will be added in a future PR. Not useful now, given the simplicity of CLI settings.

Version handling details

---

cleanlab_cli/dataset/upload_helpers.py

switching from `pd.to_datetime(column_value)` to `pd.Timestamp(column_value)` significantly speeds up processing time.

increase parsing speed of datetime with Timestamp

---

DEVELOPMENT.md
cleanlab_cli/api_service.py

With this patch, rather than modifying the `api_service.py` file for local development, a developer can run the following in their shell:
```bash
export CLEANLAB_API_URL="http://localhost:8500/api/cli/v0"
```

Allow overriding API URL with an env var

---

cleanlab_cli/dataset/upload_helpers.py

For when the schema specifies the data type to be `float`, but the value is some string like `32.0`.

Implement string->float coercion

---

cleanlab_cli/dataset/schema_helpers.py

If the dataset column is an empty string, no spec is generated for it in the schema.
If the schema describes a column name that is an empty string, an error is thrown.
Upload fails for datasets with empty column names since they cannot be saved to DB.

No empty strings for column names

---

cleanlab_cli/main.py

Having a command so users can determine the version of the installed software is really helpful for debugging users' issues.

Add version command

---

cleanlab_cli/dataset/schema_types.py
cleanlab_cli/dataset/upload_helpers.py

This should improve how we handle a couple corner cases we noticed during testing.
If float is chosen as data type:
1) convert to float before parsing with pandas.Timestamp(), 
Ex:
_expected datetime but unable to parse '1.413324556E+09' with string type_
2) extract floating number from a string
Ex:
_expected 'float' but got '34%' with string type_

float conversion for timestamp and regex for float string

---

README.md

Re-ordering instructions to match the canonical order that most users do which is to just upload instead of generating a schema. the less common workflow should be put second.

Put upload dataset before schema gen.

---

.github/workflows/tag-and-release.yml

Introduces a new GH action workflow that builds the `cleanlab-cli` package and uploads it to PyPi, every time a release tag commit is pushed to the `main` branch.

Tag and release gh action

---

cleanlab_cli/classes/excel_dataset.py
cleanlab_cli/dataset/schema_helpers.py

We received a bug in production for cleanlab-studio.
The bug originated from
`File "/usr/local/lib/python3.10/site-packages/cleanlab_cli/dataset/schema_helpers.py", line 47, in _find_best_matching_column`
The utility expects string columns but received int columns.
This will fix the bug for now. @calebchiam - Maybe you will have more context on why the function received int columns in the first place. Let me know if there is a better solution.
**Limitation**
This will fail if the columns are not castable to string

convert to str explicitly

---

cleanlab_cli/api_service.py
cleanlab_cli/dataset/schema.py
cleanlab_cli/dataset/schema_helpers.py
cleanlab_cli/dataset/schema_types.py
cleanlab_cli/dataset/upload.py
cleanlab_cli/dataset/upload_helpers.py
cleanlab_cli/dataset/upload_types.py
cleanlab_cli/types.py
requirements_dev.txt
setup.py
tests/requirements_test.txt

This PR improves on #37 by rewriting most of the `TypedDict` and `Literal` instances as `dataclass` and `Enum` instances respectively. 
This makes for some cleaner code:
- No more string literals, just enum values
- Simplified `validate_schema`, since the Dataclass and Enum types enforce that the schema contains all relevant keys and that Enum-casted values are valid
Also simplifies some typing issues going forward, as we would need `typing-extensions` for constructs like `NotRequired` for image modality-related schema changes.
PR also includes a few image modality related changes.

Refactor: TypedDict -> Dataclass, Literal -> Enum

---

.mypy.ini
cleanlab_cli/api_service.py
cleanlab_cli/cleanset/download.py
cleanlab_cli/cleanset/download_helpers.py
cleanlab_cli/dataset/helpers.py
cleanlab_cli/dataset/image_utils.py
cleanlab_cli/dataset/schema.py
cleanlab_cli/dataset/schema_helpers.py
cleanlab_cli/dataset/schema_types.py
cleanlab_cli/dataset/upload.py
cleanlab_cli/dataset/upload_helpers.py
cleanlab_cli/dataset/upload_types.py
cleanlab_cli/types.py
cleanlab_cli/util.py
setup.py

This PR introduces:
- Schema generation for image datasets
- Upload checks for image datasets, except for the actual images themselves getting uploaded (pending Studio backend changes)
- `filepath_column` is now an optional field for Schema metadata, meant to specify the column holding image (or media) filepaths
- New `ValidationWarning`s: `MISSING_FILE` and `INVALID_FILE`
- Switches to POST requests with JSON instead of Form data
- Small improvements to existing behavior + bug fixes
Merging in these changes first so that we can release an alpha package version for backend to use and incorporate.

Partial image support and other small improvements

---

cleanlab_cli/api_service.py
cleanlab_cli/dataset/upload_helpers.py

Previously, authenticating HTTP requests made by the CLI was non-standard as API keys were passed as form data.
This PR changes all HTTP requests to send JSON data and to use bearer-style authentication headers.
- Also fixes a small bug in converting `Decimal` values when processing datasets

Switch to Bearer-style authentication + send requests with JSON data

---

cleanlab_cli/api_service.py
cleanlab_cli/dataset/image_utils.py
cleanlab_cli/dataset/schema.py
cleanlab_cli/dataset/upload.py
cleanlab_cli/dataset/upload_helpers.py
cleanlab_cli/dataset/upload_types.py
cleanlab_cli/login/login.py
cleanlab_cli/util.py

- Standardized image errors to two types: `MISSING_FILE` and `UNREADABLE_FILE`. In both cases, the row is skipped, i.e. not uploaded
- Image file paths must either be absolute or relative to **the directory containing the dataset labels file**.
- Shortened most prompts by deleting "Would you like"
- At the end of dataset upload, if this is an image dataset and some rows failed due to missing / unreadable file, the user is prompted if they would like to conclude the upload or pick up later
- Implement logic for getting and using the presigned posts
Note: still debugging some localstack issues

Remaining image support changes

---

cleanlab_cli/dataset/upload_helpers.py
tests/commands/test_schema.py
tests/row_processing/test_boolean_data_type.py
tests/row_processing/test_datetime_feature_type.py
tests/row_processing/test_float_data_type.py
tests/row_processing/test_integer_data_type.py
tests/row_processing/test_string_data_type.py
tests/row_processing/utils.py
tests/unit/test_extract_float_string.py

Introduces a new test suite at `tests/row_processing` that checks that dataset values are parsed / handled correctly based on the specified schema data type / feature type. 
Unit tests for the `extract_float_string` function are also introduced.
This test suite actually caught several bugs, which are fixed in this PR as well.
- Fixes bug where 'whole' floats like 1.0, 2.0, etc were not correctly cast to the corresponding integer when the data type is set to `integer` (fixes issue: https://github.com/cleanlab/cleanlab-studio/issues/574)
- Fixes bug where float strings (e.g. `'180.0'`) were replaced with `None` for `integer` data type. Now fixed so that this is converted to `180`. Note that `180.5` is still replaced by `None`.
- Fixes bug where for datetime feature types, if the value was a …

Tests: Unit tests for processing values based on datatypes and datetime feature type

---

cleanlab_cli/dataset/upload_helpers.py
tests/unit/test_extract_float_string.py

This PR fixes the regex in `extract_float_string`, which resolves the following issues:
- Negative signs were being dropped, e.g. `extract_float_string("-180")` returned `"180"` instead of `"-180"`
- Resolves #33 (we were not able to handle $ and % in strings)
- Invalid strings like `extract_float_string("c2ab3")` returned `"2"` and `extract_float_string("cc982")` returned `"982"`, instead of `""`
Adds a fuller test suite for `extract_float_string`. All tests pass now.

Fix regex for extracting floats/ints from strings + add more test cases

---

cleanlab_studio/cli/main.py

This makes `cleanlab version` faster and also makes it avoid relying on our API. We might ask users to run `cleanlab version` to help us with debugging, and so this command should be as robust as possible.

Skip checking version compat for "version" command

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/dataset/schema_types.py

We need to be careful with dict representations of things versus internal representations (like the Schema object).
This bug was preventing resuming uploads from working.

Fix type error

---

cleanlab_studio/cli/dataset/schema_helpers.py

It's a little confusing if our CLI suggests [id] column for the filepath column. This could lead to user errors if they rely on our defaults.
Before, we essentially checked for a direct match against our target columns of `id` or `filepath`, which is too stringent. For example, it's unlikely a random user's filepath column is exactly titled `filepath`, but it's much more likely that it contains the word `file`. This compares the column name against a regex that contains likely substrings of the target column.
Resolves https://github.com/cleanlab/cleanlab-studio-integration/issues/675

improve suggestions with regex search over direct match

---

README.md
cleanlab_studio/cli/dataset/upload.py

Implementation is a little hacky, especially with the synthesizing of the CSV metadata file and writing it to disk, but it works :) It seemed like the simplest solution without major refactoring.
Tested locally with a couple datasets. Would appreciate it if others could also test, both fresh upload + resuming an upload.
The caltech256 dataset and CIFAR10-NOISY20 dataset are formatted in a way compatible with simple image upload, but you can do other datasets too. The CreateColorsDataset tool also outputs datasets compatible with simple image upload.

Add simple image upload

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/dataset/upload_helpers.py
cleanlab_studio/cli/util.py

Part of the solution for https://github.com/cleanlab/cleanlab-studio-integration/issues/751:
This limits limits max uploaded dataset size for image datasets, similar to how we check for text/tabular datasets. Instead of checking one dataset file size, we sum the sizes of all files in the upload. (*Value is set to 5GB for now)

check_dataset_limit for image datasets

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/dataset/upload_helpers.py
cleanlab_studio/version.py

Instead of `check_dataset_limit` only checking whether or not the dataset is an image dataset, it sends the actual modality to the backend (i.e. text, tabular, image)

check_dataset_limit by dataset modality

---

cleanlab_studio/cli/classes/excel_dataset.py

- convert timestamps to strings when loading ExcelDatasets
Tested with [bad.xslx](https://github.com/cleanlab/cleanlab-studio-integration/files/9675451/bad.xlsx) and [bad_numbers.xslx](https://github.com/cleanlab/cleanlab-studio-integration/files/9675408/bad_numbers.xlsx) and running:
```python
from cleanlab_studio.cli.dataset.schema_helpers import *
print(propose_schema('bad.xlsx'))
```

Fix: Excel timestamp handling

---

setup.py

https://github.com/pyexcel/pyexcel-xlsx/issues/52
`openpyxl-3.1.0` breaks `read_sheet`. Pinning to 3.0.10 fixes

Hotfix: pin openpyxl version to 3.0.10

---

cleanlab_studio/cli/dataset/upload_helpers.py

Add a `base_directory` param to `validate_and_process_record` so that we can successfully validate datasets with relative filepaths.
We are adding support for simple image zip upload through the UI. Since we don't want to expose our internal storage organization to users, we want to write only the relative file path of an image to the dataset. The `validate_and_process_record` function is called on every row of a dataset created from the UI before saving the dataset. The validation in this function will fail if a file does not exist. We are updating it to take in a `base_directory` parameter and join that with the file path in the dataset record before checking that the file exists.
- Check that uploading a simple image zip dataset using these [frontend …

add relative path support to dataset record validation

---

cleanlab_studio/cli/dataset/upload_helpers.py
tests/row_processing/utils.py

Allow disabling of filepath existence/readability checks in `validate_and_process_record`. This will be used when uploading a dataset via ZIP file since we don't extract the ZIP file contents, so the `image_file_exists` and `image_file_readable` checks will fail.
- Unit tests pass
- Tested w/ changes in https://github.com/cleanlab/cleanlab-studio-backend/pull/273 and https://github.com/cleanlab/cleanlab-studio-frontend/pull/277

add flag to disable file existence checks in validation

---

cleanlab_studio/cli/dataset/upload.py
cleanlab_studio/cli/dataset/upload_helpers.py

Fixes a bug with simple image upload on Windows. Tempfiles are not guaranteed to be accessible outside the original function they were created in on Windows. This led to errors when attempting to create a dataset using the temporary metadata file written for simple image datasets. This fix will use a StringIO object instead of tempfile to write the simple image metadata like we're doing for simple image zip upload through the UI.
- Verify that uploading a simple image dataset through CLI works
- Verify that uploading an image dataset using a manifest CSV works
- Verify that uploading text/tabular datasets still work
- Check that the above uploads work when resuming an upload that was incomplete as well

Fix: fix simple image upload bug on windows

---

.mypy.ini
cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/dataset/schema.py
cleanlab_studio/cli/dataset/schema_helpers.py
cleanlab_studio/cli/dataset/schema_types.py
cleanlab_studio/cli/dataset/upload.py
cleanlab_studio/cli/dataset/upload_helpers.py
cleanlab_studio/cli/types.py
setup.py

CLI changes to support uploading externally hosted media datasets.
- Pull changes from `feat/external-media-upload` branch in `cleanlab-studio` and `cleanlab-studio-backend` repos
- Run studio app locally
- Try uploading dataset containing image urls from CLI (example: [dog_breeds_img_url_dataset.csv](https://github.com/cleanlab/cleanlab-studio/files/10798985/dog_breeds_img_url_dataset.csv))
- Make sure other image upload formats still work from CLI (simple image upload, csv manifest upload)
- Check if datasets were uploaded successfully in frontend (will need to pull from `feat/external-media-upload` branch in frontend repo for images to render properly when viewing project)

externally hosted media upload support

---

cleanlab_studio/cli/util.py

Currently uploading a dataset with a capitalized file extension fails https://github.com/cleanlab/cleanlab-studio-integration/issues/872
Closes cleanlab/cleanlab-studio-integration#872

(easy) Fix: make get_dataset_file_extension case insensitive

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/dataset/upload_helpers.py

@axl1313 was causing the backend to spill over its SQLAlchemy pool capacity by sending too many uploads in parallel. This change throttle the number of parallel uploads to prevent this from occurring.
This is a stop gap fix that will suffice until the data ingestion service is done.

Fix: throttle number of parallel uploads

---

cleanlab_studio/studio/studio.py

df.join(other, on=...) always uses other's index, but uses the index column from df (an alternative is to set the index column for df as well, but that would mutate the df, which we want to preserve in this case). The rsuffix is not necessary: we don't expect there to be any other overlapping columns in cl_cols.
Later, when adding the __cleanlab_final_label column: we can't use cl_cols on the rhs of the assignment, because that DataFrame's index doesn't match the joined_ds, instead we should just use joined_ds.
Finally, we shouldn't mutate the DataFrame that was passed in, we should return a new DataFrame that has the corrections applied (later, we could expand the API to include an inplace=True kwarg).

Fix join bugs with Pandas DataFrames

---

cleanlab_studio/cli/dataset/upload.py
cleanlab_studio/studio/upload.py

This change is meant to support changes in https://github.com/cleanlab/cleanlab-studio-data-ingestion/pull/35 while being backwards compatible
Detailed context here: https://www.notion.so/cleanlab/1271-d1d13ce18eeb4d0083001276c65a8a29?pvs=4
- Check that uploading simple zip, zip w/ metadata, and text/tabular datasets work using cli and python API with just these changes
- Check that uploading simple zip, zip w/ metadata, and text/tabular datasets work using cli and python API with this change + data ingestion changes

backwards compatible change to support better simple zip schema handling

---

DEVELOPMENT.md
cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

Adds support for creating projects through they Python API. User must supply dataset_id and project_name parameters. All other project fields are specified through optional kwargs. For fields that aren't supplied by the user, we make our best guess (similar to how the frontend supplies defaults)
- Test with backend changes in feat/python-api-project-creation
- Test that creating projects works for all modalities
- Try various combinations of user supplied and inferred project fields

Feature: add support for creating projects through the python api

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/main.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

Fix to properly check client version in python api when initializing Studio object. Also fixes issue with CLI introduced in #92 which led to a mismatch between the base urls used by the old cli `api_service` and new shared `api` module. Eventually, we should migrate the CLI to only use shared `api` module
- tested by editing version locally to invalid version

properly check client version in python api

---

cleanlab_studio/studio/studio.py

Creating a tabular project w/ the python api and using the default for feature columns will fail right now since the full list of distinct columns from dataset details contains the label column. This leads to a duplicate column error during training. This PR removes the label column from `feature_columns` in the default case and adds validation to raise an error if user supplied feature columns overlap with label column

Fix: make sure feature columns and label column don't overlap

---

cleanlab_studio/studio/studio.py
cleanlab_studio/studio/upload.py

This PR adds support for running apply_corrections for a project with autogenerated ID columns for both pyspark and pandas dataframes. For projects created from datasets w/ autogenerated IDs we just join the corrected labels with the original dataframe in sorted order
We want to make autogenerated ID columns the default as we move away from requiring user specified ID columns
For both pyspark and pandas datasets:
- Upload a dataset specifying id_column="cleanlab-autogenerate-id"
- Create a project and make some corrections. Also use exclude action for some rows
- Run `studio.apply_corrections()`. Check that rows w/ corrections have corrected label and rows w/ exclude action are properly excluded

add support for applying corrections to dataset w auto gen id

---

cleanlab_studio/studio/studio.py

Add option to keep excluded data and return the entire dataframe in `apply_corrections`. If `keep_excluded==True`, also include the action column to indicate which examples should be excluded

add keep_excluded option in apply corrections

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

convert directly from json to pyspark dataframe in download, avoid going through pandas dataframe and dealing with <NA>

convert directly to spark dataframe from download

---

cleanlab_studio/internal/dataset_source/filepath_dataset_source.py

Fixes bug where we attempt to get file type from dataset name instead of filepath for datasets initialized from a filepath.

Fix: guess filetype from filename instead of dataset name

---

.github/workflows/tag-and-release.yml
DEVELOPMENT.md
cleanlab_studio/studio/studio.py

This PR adds docstrings for all user facing Python API functions in the format required for autogenerating the API reference on our new docs site.
To view generated API reference:
1. checkout this branch of `cleanlab-studio`
2. run `pip install --editable .`
3. clone `cleanlab-studio-docs` repo
4. run `make install` from inside `cleanlab-studio-docs`
5. run `make update-api-reference`
6. run `make docs`
7. view docs at localhost:3000

add formatted docstrings for python api

---

cleanlab_studio/studio/studio.py

Return of function currently suggests that this will return True if the cleanset is ready immediately and False otherwise, make clearer that the return of the function is blocked until cleanset is "done" being generated.

Clarify use of poll_cleanset_status function

---

cleanlab_studio/cli/api_service.py

Use the User-Agent header to add information about which version of the CLI was used to make a request. Useful for debugging. 
Closes https://github.com/cleanlab/cleanlab-studio-integration/issues/1124

add  version header to CLI

---

cleanlab_studio/studio/studio.py

Whoever can review first!
Tiny change to fix broken link in docs.
- checkout this branch of cleanlab-studio
- run `pip install -e .`
- inside of docs repo run `make update-api-reference`
- inside of docs repo run `make docs`
- navigate to http://localhost:3000/reference/python/studio/#method-get_model
- check that link documentation works

fix broken links for docs

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

@sanjanag and @anishathalye ran into a problem where rows are returned in an arbitrary order, rather than being sorted by cleanlab ID  - see [https://github.com/cleanlab/cleanlab-studio-integration/issues/1113](https://github.com/cleanlab/cleanlab-studio-integration/issues/1113 ) for additional context.
This checks for our autogenerated ID column and returns it ordered by that column if one exists. 
"Design" notes: I didn't add defensive checks such as checking if integer etc. because cleanlab_row_ID is an internal column that users' shouldn't be messing with. I also didn't reindex because 1) unneccesary computation; could slow export for big datasets and 2) autogenerate ID is autoselected and many users have other ID columns :)

sort by cleanlab-generated ID if one exists

---

cleanlab_studio/internal/clean_helpers.py

`itertools.chain` is the wrong method to use, it creates a finite-length iterable, and so the code to display the spinner raises a `StopIteration` after going through the characters once.

Fix bug with using chain instead of cycle

---

cleanlab_studio/internal/clean_helpers.py

This PR fixes an issue with how cleanset progress is displayed for completed projects when polling cleanset status from the Python API. Currently, when training is complete, the progress shows up as "Cleanset Progress: Step 16/?, Ready for review!". This is because `res["step"]` is greater than total training stages when training is complete.

fix total progress state when checking cleanset progress

---

cleanlab_studio/studio/studio.py

Previously, we called the `validate` endpoint but didn't check the result. This makes it such that there will be an immediate failure when a bad API key is passed, rather than waiting until another endpoint is called (and returning a bad error message)
Closes https://github.com/cleanlab/cleanlab-studio-integration/issues/1381

Fix: fail when invalid api key is passed to Studio

---

DEVELOPMENT.md

Wait to merge this until [this PR](https://github.com/cleanlab/cleanlab-studio-docs/pull/109) is merged

Add instructions to hide deprecated methods on docs page

---

cleanlab_studio/internal/dataset_source/dataframe_dataset_source.py
cleanlab_studio/internal/dataset_source/pandas_dataset_source.py
cleanlab_studio/internal/dataset_source/pyspark_dataset_source.py
cleanlab_studio/internal/upload_helpers.py

Part of a number of PRs that enable better handling of unlabeled data upload for multi-label data. Desired changes:
- csv upload: treat empty values as null 
- json upload: keep empty strings as is 
- support `metadata.json` for image zip upload
- Change default Python API upload to use JSON (this PR)
- for multi-label projects, treat null label as unlabeled, and treat empty-string labels as having no label
Upload dataset with both empty strings and NULLs, check (in postgres is fine) if empty strings are included in IS NULL query.

change default upload df type to json

---

cleanlab_studio/studio/studio.py

small fix to add "regression" to the typing for the `task_type` input to `studio.create_project()`

add regression to task_type typing

---

cleanlab_studio/studio/inference.py

Currently get errors when running multi-label inference if a row has no suggested labels. This PR adds handling for this edge case.

handle NA values for multilabel inference

---

cleanlab_studio/internal/api/api.py

This PR wraps the cleanset json in StringIO when downloading cleanlab columns to avoid getting a FutureWarning from pandas.read_json(). Closes https://github.com/cleanlab/cleanlab-studio-integration/issues/1498
---
- https://app.asana.com/0/0/1206261687873254

fix future warning when calling pandas read_json

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

Adds support for creating projects with no label column through the Python API. These projects will be created using tasktype `None` (or `"unsupervised"`). See associated [training](https://github.com/cleanlab/cleanlab-studio-training/pull/492) and [backend](https://github.com/cleanlab/cleanlab-studio-backend/pull/1061) PRs for more info.
---
- https://app.asana.com/0/0/1206247072076449

support creating projects w no tasktype (fully unlabeled)

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/util.py

Improve the error message for invalid UUIDs when calling APIs with e.g. cleanset id, dataset id, ...
This also handles these errors and doesn't trigger an error in the app.

Check IDs for if they are valid UUIDs

---

cleanlab_studio/internal/dataset_source/snowpark_dataset_source.py

We switched to converting dataframes to json when uploading through the Python API a few months ago. When implementing the snowflake dataframe upload, we likely were testing based on an older version of the Python API from before that change. This PR updates the snowflake dataframe source to convert to json.

convert to json rather than csv for snowflake upload

---

cleanlab_studio/internal/clean_helpers.py
cleanlab_studio/studio/studio.py

This PR updates the `wait_until_cleanset_ready()` method to print a link to the cleanset page when ready to make it easier for a user to navigate to their cleanset

print link to cleanset when ready

---

.github/workflows/format.yml
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/api/api_helper.py
cleanlab_studio/studio/trustworthy_language_model.py

Two main changes:
- Refactors TLM API to use `prompt` and `get_confidence_score` as batch methods
- `batch_prompt` and `batch_get_confidence_score` kept for reverse compatibility
- Refine retries
- Don't deduct from retry count when hitting the rate limit
- Set default retries to nonzero (now set to 1)
---
- https://app.asana.com/0/0/1206627753448625

Patch: TLM batch APIs

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/cli/click_helpers.py
cleanlab_studio/cli/dataset/schema_helpers.py
cleanlab_studio/cli/util.py
cleanlab_studio/errors.py
cleanlab_studio/internal/upload_helpers.py
cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_language_model.py

- Adds deprecation warnings if a user provides `id_column` or `modality` kwargs to the `upload_dataset` method
- Adds a deprecation warning if a user provides `schema_overrides` in the old format
- Attempts to convert old `schema_overrides` format to new format
- If feature_type is "datetime" or "identifier", raises error
- If data_type, feature_type combination is invalid in old schema format, raises error
---
- https://app.asana.com/0/0/1206603310631125

add deprecation warnings and schema override conversion

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/upload_helpers.py

- include schema overrides as part of confirm upload instead of requiring additional schema ingestion
- check for error status when polling ingestion progress
Test with [associated backend changes](https://github.com/cleanlab/cleanlab-studio-backend/pull/1211)

[upload v1] support schema overrides during initial upload

---

cleanlab_studio/internal/util.py

Bug fix:
Currently when the `apply_corrections_pd_df` function is called where the label column is of type integer, then it'll throw `TypeError: only integer scalar arrays can be converted to a scalar index`. It appears this error is due to the use of `.tolist()` method on a pandas Series that is being used as an indexer. In pandas, when you use a Series or a list as an indexer, it expects the list or Series to be of boolean type, not integer. 
solution:
The `where` function here is used to replace values where the condition is `False`, because we are replacing null values in the `corrected_label` column with the corresponding values from the `label_column` of the dataset. We can achieve this instead by using the `fillna` function.

Fix - populate final label in apply_corrections_pd_df with fillna

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py

Raise 4XXs from TLM immediately, don't retry
---
Testing:
Run the TLM, providing invalid options. TLM should fail ~immediately without retrying, with a `TlmBadRequest` error type:
E.g:
```
tlm = Studio("<API_KEY>").TLM()
tlm.prompt("2+2?", options={"some_invalid_option": 123})
```
---
- https://app.asana.com/0/0/1206649294650263

Patch: dont retry tlm 4XXs

---

cleanlab_studio/internal/api/api.py

handle rate limits before tlm client errors
(ensure rate limits get retried
Fixes bug introduced https://github.com/cleanlab/cleanlab-studio/pull/193

Hotfix: rate limit error precedence

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/clean_helpers.py
cleanlab_studio/studio/studio.py

This PR contains a few updates to label column validation when creating projects through the Python API:
- Improved error message if label column does not have valid type. Type validation is done in backend in dataset details endpoint.
- Adds column diversity validation for multi-class projects
- Adds validation for multi-label label columns
More context in [notion](https://www.notion.so/cleanlab/Label-column-validation-0fe0f7897f9340288859bcf3f65e6cca?pvs=4)
Note: must be merged after [backend changes](https://github.com/cleanlab/cleanlab-studio-backend/pull/1373)
Test w/ [backend changes](https://github.com/cleanlab/cleanlab-studio-backend/pull/1373)
- Attempt to create multi-class tabular project w/ label column containing < 2 classes w/ >= 5 examples each. This should fail.
- Attempt …

add better validation for project label column

---

cleanlab_studio/studio/studio.py

This patch fixes "name" and "method" showing up in the list of global variables defined by this module (which was being rendered in the docs).
There are some other preexisting problems with the telemetry, including missing telemetry for the Model and TLM classes; this patch does not address those issues.
Before:
After:

Fix variables showing up in docs as globals

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py
cleanlab_studio/version.py

This PR fixes an issue that could occur when merging cleanlab columns with the original dataset. After sorting cleanlab columns by id column, it was possible for the index of the dataframe to no longer be in sorted order. Adding the [`ignore_index` parameter](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html) when sorting the dataframe ensures that the resulting dataframe's index column is of the form 0, 1, ... n-1 so that we can merge with the original dataset using `df.merge(cleanlab_columns, left_index=True, right_index=True)` properly.
- Tabular quickstart tutorial is an example of a tutorial where merging results was broken before this change. Can run this tutorial and check that results are the same as in the Web UI.

fix dataframe index when downloading cleanlab columns

---

cleanlab_studio/version.py

to ensure developers don't forget to update the backend min client version. Sometimes users on old client versions may get opaque errors, if the backend didn't give them a clear alert that they need to upgrade their client

add reminder about backend considerations when version bumping

---

cleanlab_studio/studio/studio.py

Broken link prevents prs from passing in cleanlab-studio-docs like [here](https://github.com/cleanlab/cleanlab-studio-docs/actions/runs/8714712771/job/23905403911)

[TLM documentation] fix broken link

---

cleanlab_studio/internal/api/api.py

This line below is causing deprecation warnings to appear wherever this line is used, namely in the cleanlab studio [multiannotator tutorial](https://help.cleanlab.ai/tutorials/multiannotator/).
`pd_data: pd.DataFrame = pd.read_json(res_json[name], orient='records')`
The following line in the multiannotator tutorial is what is returning the deprecation warning:
`pred_probs = studio.download_pred_probs(cleanset_id)`
The warning can be seen below:

Updated download_array to properly read from literal string using StringIO wrapper

---

cleanlab_studio/utils/data_enrichment/enrich.py
cleanlab_studio/utils/data_enrichment/enrichment_utils.py

The build for help.cleanlab.ai is [currently broken](https://github.com/cleanlab/cleanlab-studio-docs/actions/runs/8913117520/job/24485792921) since there are some places in the docstrings for the data enrichment utils that contain unescaped angled brackets (<>). Since docusaurus converts pages to HTML, these are interpreted as unclosed JSX tags. Adding backticks around these fixes the build issue (and also makes the formatting for these regex examples nicer imo).
- Checkout this branch of `cleanlab-studio`
- Run `pip install -Ue .`
- Inside of `cleanlab-studio-docs`, run `make update-notebooks && make update-api-reference && make docs`. Check that building docs succeeds. Navigate to `localhost:3000` and check that API reference docs for data enrichment utils look correct.

add backticks around regex examples in docstrings

---

cleanlab_studio/studio/trustworthy_language_model.py

As seen in[ this on call alert](https://app.datadoghq.com/logs?query=env%3Aproduction%20service%3AFARGATE_BACKEND_CONTAINER%20%28%40status%3A%5B500%20TO%20599%5D%20OR%20%40levelname%3AERROR%29%20-%40route%3A%22%2Fapi%2Fv0%2Ftrustworthy_llm%2Fprompt%22%20-%40route%3A%22%2Fapi%2Fv0%2Ftrustworthy_llm%2Fget_confidence_score%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY8YgItVj7gwYwAAAAAAAAAYAAAAAEFZOFlnSTVJQUFEaVBHdFVaUjB5MWdBQQAAACQAAAAAMDE4ZjE4ODgtNjYyMi00MDA4LWJmMTMtMmQ3NTYwYWU3YzRm&fromUser=true&messageDisplay=inline&refresh_mode=sliding&source=monitor_notif&storage=hot&stream_sort=desc&viz=stream&from_ts=1714102749000&to_ts=1714103049000&live=false) (see logs below), when there is no running event loop, calling `get_event_loop` during TLM initialization …

Handle case when there is no running event loop

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py
cleanlab_studio/version.py

Add `Studio.delete_dataset` method to API
Backend endpoint is live in `dev` and `staging`
Backend PR: https://github.com/cleanlab/cleanlab-studio-backend/pull/1523

Feature: add delete method to dataset API

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/tlm/concurrency.py
cleanlab_studio/version.py

Patch: deberta success rate throttle

---

cleanlab_studio/internal/enrichment_utils.py
cleanlab_studio/utils/data_enrichment/enrich.py
cleanlab_studio/version.py

- change how regex is being used: support both extraction (matching) and replacements
- set default model used as `claude-3-haiku`
blocked by the merge of https://github.com/cleanlab/cleanlab-studio/pull/230 (which allows the use to claude models)
```python
data = pd.DataFrame({"inputs": ["1, 1, 1", "1, 2, 3", "1, 2, 3.5", "2, 4, 6"]})
prompt = "What is the sum of given numbers? Respond in the format 'The sum is: <sum>'. Numbers: {inputs}"
initial_results = enrich_data(studio, data, prompt, subset_indices=None)
initial_results = data.join(initial_results)
process_regex(initial_results["metadata"], ('\D', '')) 
process_regex(initial_results["metadata"], [('.*The sum is:', ''), ('\.$', "")])
process_regex(initial_results["metadata"], ".*The sum is: (.*)")
results = enrich_data(studio, data, …
```

Improve data enrichment functions

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/types.py
cleanlab_studio/studio/enrichment.py
cleanlab_studio/studio/studio.py

This adds the ability to add, delete, and list Enrichment Projects.
```py
>>> ep = studio.create_enrichment_project(dataset_id="ad409cee4080496587e770c9c6ba97b2", name="hello-world")
>>> ep.to_dict()
{'id': 'd498d2e62f9a4ec6910ff45cd09e47d2', 'name': 'hello-world', 'created_at': datetime.datetime(2024, 6, 6, 0, 1, 55), 'updated_at': datetime.datetime(2024, 6, 6, 0, 1, 55)}
>>> studio.get_enrichment_projects()
[<cleanlab_studio.studio.enrichment.EnrichmentProject object at 0x10041d750>, <cleanlab_studio.studio.enrichment.EnrichmentProject object at 0x12aeb4850>, <cleanlab_studio.studio.enrichment.EnrichmentProject object at 0x12aeb4ee0>, <cleanlab_studio.studio.enrichment.EnrichmentProject object at 0x12aeb4f10>]
>>> studio.delete_enrichment_project(project_id=ep.id)
Successfully deleted …
```

Add ability to add, delete, and get enrichment project(s)

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

I'm updating this line to have more a modern and explicit type annotation for numpy floats. `np.float_` is removed in later NumPy versions

Mypy fix - update np.float_ to np.float64

---

cleanlab_studio/cli/login/login.py
cleanlab_studio/errors.py

Use AuthError instead of abort() for Invalid API keys to reduce the alert noise from wrong keys

change abort() to AuthError

---

.pre-commit-hooks.yaml

This file `.pre-commit-hooks.yaml` is intended to be used for repos that publish pre-commit hooks. That is not the case for this repo.
Having both this file and `.pre-commit-hooks.yaml` can mislead developers about which file they should update.

Remove .pre-commit-hooks.yaml file

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/enrichment.py

Add EnrichmentProject.preview, EnrichmentResult and EnrichmentOptions
```
if __name__ == "__main__":
import os
os.environ["CLEANLAB_API_BASE_URL"] = "https://api.dev-bc26qf4m.cleanlab.ai/api"
from cleanlab_studio import Studio
from cleanlab_studio.studio.enrichment import (
EnrichmentOptions,
TLMOptions,
EnrichmentProject,
EnrichmentPreviewResult,
)
api_key = "xxx"
dataset_id = "xxx"
project_id = "xxx"
studio = Studio(api_key)
enrichment_project = EnrichmentProject(
api_key=api_key,
id=project_id,
name="aaron_test",
created_at="Thu, 01 Jan 1970 00:00:00 UTC",
)
print(enrichment_project.id)
erich_options = EnrichmentOptions(
prompt="is ${People} a number?",
quality_preset="low",
)
result: EnrichmentPreviewResult = enrichment_project.preview(
options=erich_options, new_column_name="random", …
```

[Data Enrichment] Add EnrichmentProject.preview, EnrichmentResult and EnrichmentOptions

---

cleanlab_studio/internal/constants.py
cleanlab_studio/studio/trustworthy_language_model.py

Adds `gpt-4o` TLM model options, do not merge until backend is ready.

Add gpt-4o as TLM model option

---

cleanlab_studio/internal/api/api.py

We have some handled api errors in the backend server that return an error string instead of a dictionary with the `code` and `description` properties. ex: `abort(422, "Download failed...")`. I'm adding a check to avoid the following error and instead print the actual error string: `AttributeError: 'str' object has no attribute 'get'` . Ideally our backend responses would have a more rigorous format, but adding this lightweight check now will avoid triggering an unhandled exception and show the actual error message.

Hotfix - check that error is dict before calling .get()

---

cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_language_model.py

For https://github.com/cleanlab/cleanlab-studio-docs/issues/500

move most TLM documentation off of the main Studio docs page

---

cleanlab_studio/studio/trustworthy_language_model.py

Tested the model latency and token calculation with https://github.com/cleanlab/sandbox/blob/main/TLM-bedrock/bedrock_haiku_test.ipynb.

Add claude-3-haiku to the documentation

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/constants.py
cleanlab_studio/internal/tlm/validation.py
cleanlab_studio/internal/types.py
cleanlab_studio/studio/trustworthy_language_model.py

- Adds a new TLMOption, `log`, which allows users to specify what additional logs/metadata they want returned.
If logs is specified (by default it will be `None`):
- `tlm.prompt()` will return the same dictionary with an additional `log` key-value pair
- `tlm.get_trustworthiness_score` will return a dictionary (with `trustworthiness_score` and `log` as keys) instead of float
- Adds an new optional keyword argument to `tlm.get_trustworthiness_score` named `perplexity` which allows users to pass in perplexity scores (from their own LLM, or anywhere else) to consider as part of the scoring computation
```python
tlm_prompt = studio.TLM("base", options={ "log": ["perplexity"]})
res = tlm_prompt.prompt(prompt)
res 
>> {"response": ..., trustworthiness_score": ..., "log": {"perplexity": 0.5}} …
```

Add logs to TLM outputs + allow perplexity as input

---

cleanlab_studio/studio/trustworthy_language_model.py

Small typing update - `log` was previously wrongly specified to be `Optional` (ie. it has to be present in the dict but can have a value of `None`), but it should instead be `NotRequired` (ie. does not have to be in the dict)

Update typing for TLM log

---

cleanlab_studio/studio/trustworthy_language_model.py

This is not a valid arg, think it got accidentally copied in the docstring when moving from studio -> trustworthy_language_model module

docs fix: remove api_key arg from docstring of TLM

---

cleanlab_studio/studio/studio.py

to fix broken docs build:
I'm not sure this is the fix, just getting it started. The broken build is preventing TLMHybrid from showing in the docs and the advanced tutorial. Once the fix is in, please verify these two things both look good on help.cleanlab.ai

fix broken documentation link

---

cleanlab_studio/cli/util.py

Catches `ValueError` and raises `InvalidDatasetError` (which is a handled error) instead when an invalid file extension is provided to `get_dataset_file_extension()` so that we don't get alerted

handled error for invalid dataset file extension in cli

---

cleanlab_studio/internal/api/api.py

Once this bugfix is merged in, please ask @aditya1503 why #benchmark-studio regression tests did not catch this.
This is high-priority bug that affects API users.

[bugfix] "ModuleNotFoundError: No module named 'snowflake.snowpark'" that happens when running Studio API tutorials

---

cleanlab_studio/internal/constants.py
cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/utils/tlm_hybrid.py
cleanlab_studio/version.py

Adds new method `get_model_name()` to easily know which model the TLM is using.
I've also explicitly specified which default model is being used in the client API call to the backend. Currently, if no model is specified from the client, we use the default in the backend but this `get_model_name()` method can get outdated if someone uses an older version of the client library against an updated backend.
Sample usage:
```python
tlm = studio.TLM()
tlm.get_model_name()
>> 'gpt-4o-mini'
```
```python
tlm = studio.TLM(options={"model": "claude-3-haiku"})
tlm.get_model_name()
>> 'claude-3-haiku'
```
```python
tlm_hybrid = studio.TLMHybrid()
tlm_hybrid.get_model_names()
>> {'response_model': 'gpt-4o', 'score_model': 'gpt-4o-mini'}
```

Add method to print TLM model name

---

cleanlab_studio/errors.py
cleanlab_studio/studio/enrichment.py

The `wait_until_ready` function is designed to wait until the latest enrichment job is completed. It uses a progress bar to provide visual feedback on the job's progress.
- `num_rows` is the total # rows for the dataset and comes from the enrichment project dict. `processed_rows` is the value of currently processed rows and comes from the enrichment job status endpoint. these are used in the progress. the loop continues until `self.ready` is `True`
- `_get_num_processed_rows` helper function, because the status endpoint only returns the `processed_rows` property if the status is running. note: we may want to include this logic in the backend instead of python client
- refactored `self._latest_populate_job` to use `_get_latest_job` helper function. the previous implementation was …

[DE] implement `wait_until_ready` function for `EnrichmentProject`

---

cleanlab_studio/studio/trustworthy_language_model.py

Does not try to return log if an empty list is passed into the `log` option. The following should work properly now:
```python
tlm = studio.TLM(options={"log": []})
res = tlm.prompt("What are the colours of a rainbow?")
```

[TLM] Handle empty log list

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

This code snippet was erroring out due to a bad type check:
```python
tlm = studio.TLM() 
trustworthiness_score = await tlm.get_trustworthiness_score_async("what is 1+1", response="2")
```
This PR should fix that.

[TLM] Fix get_trustworthiness_score_async type check

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

This change will allow our custom defined types to show up on help.cleanlab.ai [here](https://help.cleanlab.ai/reference/python/trustworthy_language_model/)

[TLM] Add custom types to docstrings

---

cleanlab_studio/internal/enrichment_utils.py

Function updates contrain outputs to return last occurrence of category instead of first. Useful in case model is asked to reason and lists other categories in its reasoning before the final category.

[TLM] Update contrain outputs 

---

.github/workflows/ci-tlm.yml

If a workflow is launched through a pull_request action, using github.event.pull_request.number to get the pr number [works great](https://github.com/cleanlab/cleanlab-studio/actions/runs/10835062351/job/30065723879?pr=303). However, [this does not seem to be true](https://github.com/cleanlab/cleanlab-studio/actions/runs/10835079271/job/30065780786) for a workflow launched through a comment action.
Bugfix attempt to use github.event.issue.number instead (since pr/issue number is the same value)

[TLM CI] update how pr/issue numbers are handled

---

.github/workflows/ci-test-tlm.yml
DEVELOPMENT.md

PR also updates action to avoid running always() when a comment is made.

[TLM CI] Add testing instructions

---

tests/tlm/test_prompt.py
tests/tlm/test_properties.py

Add args to be able to specify which configs are not expected to produce trustworthiness scores or `TLMResponse` objects

[TLM CI] Add more configurable args to unittests

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/enrichment_utils.py
cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/utils/tlm_lite.py
cleanlab_studio/version.py
tests/tlm/test_get_trustworthiness_score.py
tests/tlm/test_prompt.py
tests/tlm/test_properties.py
tests/tlm/test_validation.py

Changes:
- This is a backwards incompatible change so bumped the major version
- All the score related functions only return TLMScore objects. When it’s a successful call and no log is returned, it will be a single “trustworthiness_score” field inside the json
- Both the try_prompt() and try_get_trustworthiness_score() will no longer return None
- Changed tlm_lite in the same format as well
- In addition to the final error log output, we also raise warning to the user as well so they can be aware of
Tests:
https://drive.google.com/file/d/1v-pBme_ENiUObEnAaxdi9fmQyVR2lJyc/view?usp=drive_link

[TLM] log error msg from try_prompt and try_get_trustworthiness_score

---

cleanlab_studio/errors.py
cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/utils/tlm_calibrated.py
cleanlab_studio/version.py
setup.py

Building off the custom eval criteria in https://github.com/cleanlab/cleanlab-studio/pull/325
Sample workflow:
```python
prompts = ["what is 1+1", "what is 1+2", "what is 1+3"]
responses = ["2", "hm let me think, i think the answer is 3? am i right?", "5"]
ratings = [5, 3, 1]
custom_eval_criteria_option = {"custom_eval_criteria": [
{"name": "Conciseness", "criteria": "Determine if the output is concise."}
]}
tlm = studio.TLM(options=custom_eval_criteria_option)
scores = tlm.get_trustworthiness_score(prompts, responses)
tlm_calibrated = studio.TLMCalibrated(options=custom_eval_criteria_option)
tlm_calibrated.fit(scores, ratings)
tlm_calibrated.get_trustworthiness_score("what is 2+2", "5")
>> {'trustworthiness_score': 0.050770278656628066,
'log': {'custom_eval_criteria': [{'name': …
```

[TLM] Add TLMCalibrated class 

---

cleanlab_studio/internal/api/api.py

Add a max number of retried for connection errors so that the TLM would not hang indefinitely.

[TLM] Improve retry logic

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

Note that the ** is intentionally removed in the docstring to avoid inappropriate rendering like below

TLM constrain_outputs doc

---

cleanlab_studio/internal/constants.py
cleanlab_studio/internal/tlm/validation.py
cleanlab_studio/version.py
tests/tlm/constants.py
tests/tlm/test_validation.py

Have `constrain_outputs` to support single list of strings for batch prompt use cases.

[TLM] constrain output batch prompt update

---

cleanlab_studio/internal/constants.py
cleanlab_studio/internal/tlm/validation.py
cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py
tests/tlm/constants.py

Also add better error message for models that don't support explanation

[TLM] Add o3-mini

---

setup.py

Closes https://github.com/cleanlab/cleanlab-studio/issues/347
Allowing Click 8.1.7 and later fixes compatibility with packages like langchain that require later Click 8.1.x versions.

Allow Click 8.1.7+ for langchain etc compatibility
