cleanlab/cleanlab-studio

.github/workflows/benchmarking.yml

- Saves benchmarking stats to `output.json`
- Checks for regressions in the performance and fails the workflow if workflow degrades significantly
- Uses [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark)

Added benchmarking CI

---

cleanlab_cli/dataset/schema.py
cleanlab_cli/dataset/schema_helpers.py
cleanlab_cli/dataset/upload.py

Implemented reservoir sampling to solve the problem of: `How to sample k elements from N elements when N >> k, without first computing the value of N`
This saves us 1 out of 2 iterations through the dataset, so it should halve the time taken for the schema generation step.

Reservoir sampling

---

cleanlab_cli/api_service.py
cleanlab_cli/cleanset/commands.py
cleanlab_cli/cleanset/download.py

- Renamed command group from `experiment` to `cleanset`
- Updated API calls accordingly

experiment -> cleanset

---

cleanlab_cli/api_service.py
cleanlab_cli/dataset/upload.py
cleanlab_cli/dataset/upload_helpers.py
setup.py

Two major updates: asynchronous uploads and compressed uploads.
Tested locally with multiple datasets.
Benchmarking (note: compression AND asynchronicity updates are tested together):
-----------------------------------------------------
local testing -- no network condition dependence
Tweets 1M
aiohttp (10Mb chunk): 2.68s
sync (10Mb chunk): 3.01s
Tweets 10M
aiohttp (1Mb chunk): 10.88s
aiohttp (10Mb chunk): 11.48s
sync (10Mb chunk): 29.66s
Tweets 100M
aiohttp (1Mb chunk): 98.74s
aiohttp (10Mb chunk): 88.63s
sync (10Mb chunk): <gateway timeout error>

Feature: async cli upload

---

cleanlab_cli/click_helpers.py

Remove recommended editors

---

cleanlab_cli/api_service.py

async uploads

---

cleanlab_studio/cli/api_service.py

This patch adds retries with exponential backoff to S3 uploads. The implementation in this patch isn't ideal, because it only makes the failed upload back off, but all other coroutines (up to 31, with the current choice of parameters) continue uploading as before. Still, it seems to mostly alleviate the problem with failed S3 uploads due to rate limiting or transient errors.

Add basic retry logic for S3 uploads

---

README.md

README still needs work, but I think this should help people get started.

Add a quickstart section

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/version.py

- Bump version to 0.1.17
- Pass row IDs to generate presigned posts endpoint

Feature: s3 object key generation using hash

---

cleanlab_studio/cli/dataset/upload_helpers.py

- fixes off by 1 error with process dataset progress bar
Closes: https://github.com/cleanlab/cleanlab-studio-integration/issues/683

Fix: process dataset progress bar off-by-1

---

cleanlab_studio/cli/dataset/upload.py

Before: stack trace. After: error message about missing file/directory.
CC @cgnorthcutt

Add better error message for missing filepath

---

cleanlab_studio/cli/classes/csv_dataset.py
cleanlab_studio/cli/dataset/schema_helpers.py
cleanlab_studio/errors.py

- Adds custom errors for:
- ColumnMismatchError (number of columns in header != number of columns in data)
- EmptyDatasetError

Feature: improved schema proposition error handling

---

cleanlab_studio/cli/dataset/upload_helpers.py

fix type checking

---

cleanlab_studio/studio/studio.py

Properly applies exclude actions taken on a project when running `studio.apply_corrections()` with a pandas or pyspark dataframe
Test w/ backend change in branch `feat/send-actions-to-cli` (changes are also in dev)
- Upload a dataset from a pandas/pyspark dataframe using the Python API
- Create a project using the uploaded dataset
- Exclude some rows from the project using the studio UI
- Run `apply_corrections` using the python API
- Verify that the rows you excluded are filtered from the resulting dataframe

Feature: apply row exclusions

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py
docs/source/tutorials/python_api_demo.ipynb

This PR adds a method to the Python API for deleting projects
Test w/ backend branch `feat/python-api-project-deletion`
- Check that deleting one of your projects succeeds
- Check that attempting to delete project w invalid ID/project you don't own fails

Feature: add support for project deletion from python api

---

cleanlab_studio/cli/types.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py
setup.py

Expose api for downloading pred_probs and embeddings from training for cleansets
corresponding PRs:
training (save pred_probs and embeddings): https://github.com/cleanlab/cleanlab-studio-training/pull/211
scheduler (send user_id to training): https://github.com/cleanlab/cleanlab-studio-scheduler/pull/64
backend (api to download): https://github.com/cleanlab/cleanlab-studio-backend/pull/535

python api for downloading embeddings and pred_probs

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

allow downloaded arrays to be of pd.dataframe

download pred probs as pd dataframe

---

cleanlab_studio/cli/api_service.py
cleanlab_studio/internal/api/api.py

Add `Client-Type` in the request header to either `cli` or `python-client` to keep track of these attributes in mixpanel.

initial changes

---

cleanlab_studio/internal/clean_helpers.py

Context: We recently changed how we track training progress for cleansets. We now use the `total_training_stages` field on the cleanset rather than a fixed number (`ProjectStatus.READY.value - 1`) for `"total_steps"` in the `get_cleanset_status()` api response. `total_training_stages` is null until the training job has been initialized, so if you started polling for cleanset status before `total_training_stages` was set, the tqdm pbar's `total` would always be null. This led to issues when updating the progress on the pbar since we'd attempt to subtract from a null value.
This PR updates cleanset status tracking in the Python API to update the tqdm pbar's total field once `total_training_stages` is available.
Once this PR is merged and version is bumped, will update min cli version in …

update cleanset status pbar when total steps ready

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_llm.py
docs/source/tutorials/python_api_demo.ipynb

Adds TLM inference API
Test using the following flow:
```
from cleanlab_studio import Studio
studio = Studio(<your API key>)
tlm = studio.TLM(quality_preset=<quality_preset>)
tlm.prompt(<your prompt>)
tlm.get_confidence_score(<your prompt>, <your response>)
```

Feature: tlm inference api

---

cleanlab_studio/studio/studio.py

related GH issue: https://github.com/cleanlab/cleanlab-studio-docs/issues/85

clarify poll_cleanset deprecated in its docstring

---

cleanlab_studio/studio/inference.py
cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_language_model.py

- Fixes TLM module name
- Improves docstrings for TLM
Closes: https://github.com/cleanlab/cleanlab-studio-integration/issues/1380

Update: tlm docs

---

.github/workflows/ci.yml
cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/trustworthy_language_model.py
docs/source/tutorials/python_api_demo.ipynb

Adds configurability for `max_tokens` param of TLM. Accompanying PR up in backend
Closes: https://github.com/cleanlab/cleanlab-studio-integration/issues/1415

Feature: adds max tokens option to TLM

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

Addressing https://github.com/cleanlab/cleanlab-studio-integration/issues/1388
- fixed current failed caused because "clean_label" column has been renamed to "corrected_label"
- cleaned up [null check](https://github.com/cleanlab/cleanlab-studio/blob/017c5e37c3b2a5094dbe3e60303b0a19679d3344/cleanlab_studio/studio/studio.py#L176)

Changes to `apply_corrections` in studio.py

---

.mypy.ini
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/dataset_source/__init__.py
cleanlab_studio/internal/dataset_source/snowpark_dataset_source.py
cleanlab_studio/internal/util.py
cleanlab_studio/studio/studio.py

Adding support for `snowflake.snowpark.DataFrame` type in `upload_dataset` and `apply_corrections` api functions.

Snowpark Integration for upload_dataset and apply_corrections

---

cleanlab_studio/utils/synthetic.py
tests/utils/synthetic/dataframe.py
tests/utils/synthetic/test_synthetic.py

This PR integrates scoring helper functions from the [Synthetic Data Quality tutorial](https://help.cleanlab.ai/tutorials/synthetic_data/#quantitatively-evaluate-the-synthetic-dataset) into our package.
The intention is to streamline the tutorial by enabling direct imports of the function, rather than defining it within the tutorial itself.
- Extracted the scoring helper functions into a class in the new `cleanlab_studio.utils.synthetic` module.
- Moved the `score_synthetic_dataset` function from the tutorial into the same module.

Move scoring helper functions from Synthetic Data Quality tutorial into package

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/util.py
cleanlab_studio/studio/inference.py
cleanlab_studio/studio/studio.py

Recently enabled multilabel model deployment. This PR processes the outputs of the suggested labels, and converts them into a list of list of strings for multilabel projects.

process multi-label deployment outputs

---

cleanlab_studio/internal/upload_helpers.py

Add retries for individual part uploads

Feature: upload file part retries

---

cleanlab_studio/studio/inference.py

As title, bump time limit to slightly larger than lambdas time limit

bump model inference time limit

---

cleanlab_studio/internal/upload_helpers.py

Fixes this: https://github.com/cleanlab/cleanlab-studio-integration/issues/1431

better error message when id column doesn't exist

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/studio/studio.py

Adds poll dataset ID for name method to studio api

Feature: add poll dataset ID for name method

---

cleanlab_studio/cli/classes/dataset.py
cleanlab_studio/cli/cleanset/download.py
cleanlab_studio/cli/cleanset/download_helpers.py
cleanlab_studio/cli/dataset/schema_helpers.py
cleanlab_studio/cli/dataset/schema_types.py
cleanlab_studio/cli/dataset/upload.py
cleanlab_studio/cli/dataset/upload_helpers.py
cleanlab_studio/cli/login/login.py
cleanlab_studio/cli/main.py
cleanlab_studio/cli/util.py
cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/api/api_helper.py
cleanlab_studio/internal/dataset_source/dataset_source.py
cleanlab_studio/internal/dataset_source/filepath_dataset_source.py
cleanlab_studio/internal/dataset_source/pyspark_dataset_source.py
cleanlab_studio/internal/dataset_source/snowpark_dataset_source.py
cleanlab_studio/internal/settings.py
cleanlab_studio/internal/util.py
cleanlab_studio/studio/inference.py
cleanlab_studio/studio/studio.py

Add basic telemetry to log errors raised from the `cleanlab-studio` API usage.

Add logging for `cleanlab-studio` errors

---

cleanlab_studio/studio/studio.py

clarify `apply_corrections` docstring

---

cleanlab_studio/studio/studio.py

clarify docstrings for `download_pred_probs` and `download_embeddings`

---

cleanlab_studio/internal/util.py

remove local filepath from logged errors

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py

Context / testing information in corresponding backend PR: https://github.com/cleanlab/cleanlab-studio-backend/pull/1212

Patch: tlm query too large

---

DEVELOPMENT.md
cleanlab_studio/internal/constants.py
cleanlab_studio/internal/types.py
cleanlab_studio/studio/studio.py
cleanlab_studio/studio/trustworthy_language_model.py

- Removed global variables and functions that we don't want to display.
- Fix bad args formatting in `TLMOptions` class
Before:
After

Improve TLM docs

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py

Handle upload errors when polling for ingestion progress.
---
- https://app.asana.com/0/0/1206650326087169

Feature: upload v1 handle errors

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api_helper.py

Make invalid uuid error a handled error

handle uuid error

---

cleanlab_studio/version.py

bump version to handle invalid uuid errors

Bump version 1.2.3

---

cleanlab_studio/studio/studio.py

Adds information about unsupervised projects to create project docstring.
Closes https://github.com/cleanlab/cleanlab-studio-docs/issues/310
---
- https://app.asana.com/0/0/1206708407291721

update create project docstring for unsupervised projects

---

cleanlab_studio/studio/inference.py
cleanlab_studio/studio/studio.py

- Explain how a Model is meant to be instantiated
- Hide `csv_string_to_list` from public API

Clean up model docs

---

cleanlab_studio/version.py

Main updates:
- improved TLM docs
- fix typo causing docs to fail (#217)

Bump version (2.0.2)

---

cleanlab_studio/version.py

Main updates:
- data enrichment functionality added. 2 main functions: `enrich_data()` and `get_regex_matches()`

Bump version (2.0.3)

---

cleanlab_studio/internal/constants.py
cleanlab_studio/studio/trustworthy_language_model.py

Adds `claude-3-haiku` and `claude-3-sonnet` as TLM model options
Do not merge until we're ready to announce this

Add Claude models as TLM options

---

cleanlab_studio/internal/enrichment_utils.py
cleanlab_studio/utils/data_enrichment/enrich.py

Note: `constrain_outputs` can be potentially further improved

Improvements to constrained outputs in DE

---

.pre-commit-config.yaml
pyproject.toml

This adds isort to our pre-commit hooks.
This will help ensure a consistent style for importing modules.

Add isort to pre-commit hooks

---

cleanlab_studio/studio/enrichment.py

This updates Data Enrichment's preview to sort the returned DataFrame by Row ID.

Sort Data Enrichment Preview results

---

Enrichment_Preview_Demo.ipynb
cleanlab_studio/studio/enrichment.py

add trustworthiness_score column for join

[Data Enrichment] add trustworthiness_score column for join

---

cleanlab_studio/internal/constants.py

This will be merged after the backend change is deployed

Add sonnet 3.5 as TLM model option

---

cleanlab_studio/utils/tlm_hybrid.py
cleanlab_studio/version.py

Bumping version so TLMHybrid docs fix gets reflected

bump version (2.1.5)

---

cleanlab_studio/studio/trustworthy_language_model.py

Will merge this after the backend change is deployed

relase 4o mini and make it default model for TLM

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/utils/tlm_hybrid.py

Based on detection from https://github.com/cleanlab/cleanlab-studio-docs/actions/runs/10115560463/job/27976609950?pr=517

fix some internal link

---

cleanlab_studio/version.py

Update version to account for Studio tutorials bugfix pr

[update version] to account for tutorial bugflx

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/upload_helpers.py
cleanlab_studio/studio/studio.py

Add `upload_from_url` method to Python client

Feature: client url upload

---

cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/upload_helpers.py
cleanlab_studio/studio/studio.py

Adds BigQuery upload to Python client

Feature: add bigquery upload

---

.mypy.ini
cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/upload_helpers.py
cleanlab_studio/studio/studio.py

This PR adds support for uploading from BigFrames. It also updates the BigQuery upload implementation to set up the required permissions instead of requiring the user to do that.

add bigframe upload support

---

cleanlab_studio/errors.py
cleanlab_studio/internal/api/api.py
cleanlab_studio/internal/api/api_helper.py
cleanlab_studio/studio/enrichment.py
cleanlab_studio/studio/studio.py
setup.py

This is the new feature, data enrichment.
It will run prompts with your data to LLM and return an answer with a trustworthiness score

add data enrichment feature

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

Note: do not merge until backend changes are in

[TLM] Enable calling get_trustworthiness_score in base preset

---

cleanlab_studio/internal/api/api.py

[TLM] handle ssl exception

---

cleanlab_studio/studio/inference.py
cleanlab_studio/studio/studio.py
cleanlab_studio/version.py

Update links in conjunction with docs page re-organization: https://github.com/cleanlab/cleanlab-studio-docs/pull/566

Update docs links

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

update kwargs docstring

---

cleanlab_studio/studio/trustworthy_language_model.py

[TLM] Release more claude/nova models

---

cleanlab_studio/studio/trustworthy_language_model.py
cleanlab_studio/version.py

[docs] Improve TLM model docs

---

cleanlab_studio/studio/trustworthy_language_model.py

Fix TLMOptions docs formatting

---

cleanlab_studio/studio/studio.py

TLM deprecation message
